export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  FUNZIONI_BASE = 'GTW.FUNZIONI_BASE',
  CHANGE_PASSWORD_EXPIRED = 'CHANGE_PASSWORD_EXPIRED',
  GTW_MODIFICA_UTENTE = 'GTW.MODIFICA_UTENTE',
  GTW_ELENCO_UTENTI = 'GTW.ELENCO_UTENTI',
  GTW_ELENCO_GRUPPI = 'GTW.ELENCO_GRUPPI',
  GTW_ELENCO_FUNZIONI = 'GTW.ELENCO_FUNZIONI',
  GTW_ELENCO_PERMESSI = 'GTW.ELENCO_PERMESSI',
  GTW_STRUMENTI_CONTROLLO = 'GTW.STRUMENTI_CONTROLLO',
}
