sonar.projectKey = pagopa_pagopa-cruscotto-frontend
sonar.organization = pagopa
sonar.projectName = pagopa-cruscotto-frontend

# SonarCloud configuration for the frontend app.
sonar.host.url = https://sonarcloud.io
sonar.sources = src/main/webapp
sonar.tests = src/main/webapp
sonar.test.inclusions = **/*.spec.ts
sonar.sourceEncoding = UTF-8
sonar.exclusions = src/main/webapp/content/**,src/main/webapp/i18n/**,target/**,**/*.spec.ts
sonar.javascript.lcov.reportPaths = coverage/lcov.info
sonar.testExecutionReportPaths = target/test-results/jest/TESTS-results-sonar.xml
