/**
 * PagoPa Cruscotto Sert Backend API
 * PagoPa Cruscotto Sert Backend API documentation
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Inject, Injectable, Optional } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams, HttpResponse, HttpEvent } from '@angular/common/http';
import { CustomHttpUrlEncodingCodec } from '../encoder';

import { Observable } from 'rxjs';

import { IUnifiedSearchResponse } from '../../../entity/pago-pa/ricerca-operazioni/models/ricerca-operazioni.model';

import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';

@Injectable()
export class RicercaDellePosizioniDebitorieService {
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();

  protected basePath = 'http://localhost:8080';

  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string | null,
    @Optional() configuration: Configuration | null,
  ) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = basePath ?? configuration.basePath ?? this.basePath;
    }
  }

  /**
   *
   *
   * @param pa
   * @param nav
   * @param iuv
   * @param token
   * @param idCarrello
   * @param info
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public search(
    pa?: string,
    nav?: string,
    iuv?: string,
    token?: string,
    idCarrello?: string,
    info?: string,
    observe?: 'body',
    reportProgress?: boolean,
  ): Observable<IUnifiedSearchResponse>;
  public search(
    pa?: string,
    nav?: string,
    iuv?: string,
    token?: string,
    idCarrello?: string,
    info?: string,
    observe?: 'response',
    reportProgress?: boolean,
  ): Observable<HttpResponse<IUnifiedSearchResponse>>;
  public search(
    pa?: string,
    nav?: string,
    iuv?: string,
    token?: string,
    idCarrello?: string,
    info?: string,
    observe?: 'events',
    reportProgress?: boolean,
  ): Observable<HttpEvent<IUnifiedSearchResponse>>;
  public search(
    pa?: string,
    nav?: string,
    iuv?: string,
    token?: string,
    idCarrello?: string,
    info?: string,
    observe: any = 'body',
    reportProgress = false,
  ): Observable<any> {
    let queryParameters = new HttpParams({ encoder: new CustomHttpUrlEncodingCodec() });
    if (pa !== undefined) {
      queryParameters = queryParameters.set('pa', pa as any);
    }
    if (nav !== undefined) {
      queryParameters = queryParameters.set('nav', nav as any);
    }
    if (iuv !== undefined) {
      queryParameters = queryParameters.set('iuv', iuv as any);
    }
    if (token !== undefined) {
      queryParameters = queryParameters.set('token', token as any);
    }
    if (idCarrello !== undefined) {
      queryParameters = queryParameters.set('idCarrello', idCarrello as any);
    }
    if (info !== undefined) {
      queryParameters = queryParameters.set('info', info as any);
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    const httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected !== undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<IUnifiedSearchResponse>('get', `${this.basePath}/api/search`, {
      params: queryParameters,
      withCredentials: this.configuration.withCredentials,
      headers,
      observe,
      reportProgress,
    });
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data';
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }
}
