/**
 * PagoPa Cruscotto Sert Backend API
 * PagoPa Cruscotto Sert Backend API documentation
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */ /* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams, HttpResponse, HttpEvent } from '@angular/common/http';
import { CustomHttpUrlEncodingCodec } from '../encoder';

import { Observable } from 'rxjs';

import { IExtraInfo, ITokenInfo, ITransfers, IWorkflows } from '../../../entity/pago-pa/ricerca-operazioni/models/ricerca-operazioni.model';

import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';

@Injectable()
export class VisualizzazioneDettagliService {
  protected basePath = 'http://localhost:8080';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();

  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string,
    @Optional() configuration: Configuration,
  ) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = basePath || configuration.basePath || this.basePath;
    }
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data';
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }

  /**
   *
   *
   * @param token
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getExtraInfo(token: string, observe?: 'body', reportProgress?: boolean): Observable<IExtraInfo>;
  public getExtraInfo(token: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<IExtraInfo>>;
  public getExtraInfo(token: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IExtraInfo>>;
  public getExtraInfo(token: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (token === null || token === undefined) {
      throw new Error('Required parameter token was null or undefined when calling getExtraInfo.');
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<IExtraInfo>('get', `${this.basePath}/api/extra/${encodeURIComponent(String(token))}`, {
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress,
    });
  }

  /**
   *
   *
   * @param token
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getTokenInfo(token: string, observe?: 'body', reportProgress?: boolean): Observable<ITokenInfo>;
  public getTokenInfo(token: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ITokenInfo>>;
  public getTokenInfo(token: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ITokenInfo>>;
  public getTokenInfo(token: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (token === null || token === undefined) {
      throw new Error('Required parameter token was null or undefined when calling getTokenInfo.');
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<ITokenInfo>('get', `${this.basePath}/api/token/${encodeURIComponent(String(token))}`, {
      withCredentials: this.configuration.withCredentials,
      headers: headers,
      observe: observe,
      reportProgress: reportProgress,
    });
  }

  /**
   *
   *
   * @param nav
   * @param paEmittente
   * @param token
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getTransfers(nav: string, paEmittente: string, token: string, observe?: 'body', reportProgress?: boolean): Observable<ITransfers>;
  public getTransfers(
    nav: string,
    paEmittente: string,
    token: string,
    observe?: 'response',
    reportProgress?: boolean,
  ): Observable<HttpResponse<ITransfers>>;
  public getTransfers(
    nav: string,
    paEmittente: string,
    token: string,
    observe?: 'events',
    reportProgress?: boolean,
  ): Observable<HttpEvent<ITransfers>>;
  public getTransfers(
    nav: string,
    paEmittente: string,
    token: string,
    observe: any = 'body',
    reportProgress: boolean = false,
  ): Observable<any> {
    if (nav === null || nav === undefined) {
      throw new Error('Required parameter nav was null or undefined when calling getTransfers.');
    }

    if (paEmittente === null || paEmittente === undefined) {
      throw new Error('Required parameter paEmittente was null or undefined when calling getTransfers.');
    }

    if (token === null || token === undefined) {
      throw new Error('Required parameter token was null or undefined when calling getTransfers.');
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<ITransfers>(
      'get',
      `${this.basePath}/api/transfers/${encodeURIComponent(String(nav))}/${encodeURIComponent(String(paEmittente))}/${encodeURIComponent(String(token))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }

  /**
   *
   *
   * @param nav
   * @param paEmittente
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getWorkflows(nav: string, paEmittente: string, observe?: 'body', reportProgress?: boolean): Observable<IWorkflows>;
  public getWorkflows(
    nav: string,
    paEmittente: string,
    observe?: 'response',
    reportProgress?: boolean,
  ): Observable<HttpResponse<IWorkflows>>;
  public getWorkflows(nav: string, paEmittente: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IWorkflows>>;
  public getWorkflows(nav: string, paEmittente: string, observe: any = 'body', reportProgress: boolean = false): Observable<any> {
    if (nav === null || nav === undefined) {
      throw new Error('Required parameter nav was null or undefined when calling getWorkflows.');
    }

    if (paEmittente === null || paEmittente === undefined) {
      throw new Error('Required parameter paEmittente was null or undefined when calling getWorkflows.');
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['application/json'];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<IWorkflows>(
      'get',
      `${this.basePath}/api/workflows/${encodeURIComponent(String(nav))}/${encodeURIComponent(String(paEmittente))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      },
    );
  }
}
